name: Auto Minify JS

on:
  push:
    paths:
      - 'index.js'

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Terser
        run: npm install terser -g

      - name: Minify index.js
        run: terser index.js -o dist/index.min.js -c -m

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add dist/index.min.js
          git commit -m "auto: minify index.js to dist/index.min.js" || echo "No changes to commit"
          git push
